### ISSUE TITLE
When using nameof the constant name includes `nameof`

### ISSUE THREAD

**Issue by MarcolinoPT** [mrlacey/ConstVisualizer#10]
Hi,

Great extension, really useful :) 
Found the following issue when using it:
![image](https://user-images.githubusercontent.com/18648315/148375646-922ad650-fca5-4f1c-a3a2-5e1da830b488.png)

It displayed `nameof` as part of the constant's value.

Happens on Visual Studio 2022 v17.0.4.
Please let me know if there is any more useful information that I can provide.

Cheers!

**Comment by mrlacey** [comment]
Nice spot. I'll get on it ;)

**Comment by mrlacey** [comment]
I've just released **v1.13** to the marketplace that should address this issue.

If you have any other problems, comments, or suggestions please raise an issue.
If you love it, please [leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ConstVisualizer&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey)  :smile:
