### ISSUE TITLE
Exception - invalid parameter 

### ISSUE THREAD

**Issue by MagicAndre1981** [mrlacey/ConstVisualizer#12]
I created a new [Telerik WinUI](https://marketplace.visualstudio.com/items?itemName=TelerikInc.ProgressTelerikWinUIVSExtensions) project and saw this in output:

```
Exception 😢
-----------
Falscher Parameter. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

   at EnvDTE.DTE.get_ActiveDocument()
   at ConstVisualizer.ConstFinder.SafeGetActiveDocument(DTE dte)
```

VS2022 17.1.3 with ConstVisualizer 1.19 / Win11 (22000.593)

**Comment by mrlacey** [comment]
Thanks for reporting this. 
It's fixed in v1.20 which I've just submitted to the marketplace.
