### ISSUE TITLE
Extension loads even if no file is open

### ISSUE THREAD

**Issue by xperiandri** [mrlacey/ConstVisualizer#14]
I suppose that the extension displays info within opened code files.
But Visual Studio displays a message that it loads nevertheless no file is open which affects Visual Studio load time.
I suppose that some initialization logic must be made lazy in order not to load unnecessary.

**Comment by mrlacey** [comment]
The extension loads when an appropriate project/solution is opened as it needs to do work in the background so it has knowledge of the constants to display once a file is opened.
I'm separately, also trying to improve the loading performance so that this shouldn't be so much of an issue.
