### ISSUE TITLE
Does not work with VB.NET

### ISSUE THREAD

**Issue by ElektroStudios** [mrlacey/ConstVisualizer#17]
The extension does not work with VB.NET constants (**Const** keyword). The problem is there is no warning about this in the market place page of this extension, and because on the other hand 'String Resource Visualizer' works with VB.NET, so all this just makes a lot of confusion and one would end requiring to analyze the source-code of this extension in order to try figure out whether it is just a bug, or a non-planned support for VB.NET.

I didn't reviewed any source-code file, but I used the GitHub's search bar to try find a comment or a member nomenclature containing "vb" and "basic" keywords within the source-code files of this extension, and found nothing, so I deduce there was no planned support for VB.NET. 

Consider to add a warning in the readme.md and the market place to clarify that this extension only works for C# constants.

Thanks for all of your work, and all of your extensions.

**Comment by ElektroStudios** [comment]
Excuse me but maybe it is a bug in fact?. I just created a C# console app to test the extension but it does not work (the value of the constant is not drawn in the text editor like 'String Resource Visualizer' extension does).

I'm using Visual Studio 2022 v17.5.4 (Professional Edition) if this is can be of relevancy.

**Comment by mrlacey** [comment]
Yes, this is C# only I'm afraid (unless you want to add it.)
I'll update the readme and marketplace accordingly.
I didn't even realize that StringResourceVisualizer worked with VB.NET.
