### ISSUE TITLE
ConstVisualizer shows constant for WinForms framework calls with have same name like defined const

### ISSUE THREAD

**Issue by MagicAndre1981** [mrlacey/ConstVisualizer#3]
I have a class with implementation of [EventSource](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netstandard-2.0) with Tasks class definition like this:

```
public static class Tasks
{
    public const EventTask Application = (EventTask)1;
}
```

ConstVisualizer shows the data fine

![image](https://user-images.githubusercontent.com/8274816/89390337-d6b23400-d706-11ea-83e0-17170f87c8ce.png)

but it accidentials also shows the constant for WinForms framework calls like `Application.EnableVisualStyles();` which is confusing:

![image](https://user-images.githubusercontent.com/8274816/89390035-791de780-d706-11ea-9df7-b20d93cd3490.png)

It should only show up for the correct type usage and not every name match.

**Comment by mrlacey** [comment]
> It should only show up for the correct type usage and not every name match.

Yes.
The current implementation is a bit crude.
I can probably improve it a bit, but, as you've noted this really needs a different approach, as documented in #1

**Comment by mrlacey** [comment]
Putting in a quick workaround fix for this scenario.
Notice in the below image only one instance of `Console` has the adornment above it.

![image](https://user-images.githubusercontent.com/189547/89543873-62a48880-d7f9-11ea-9d85-d13538066c9e.png)

**Comment by MagicAndre1981** [comment]
yes, it is now fixed, but I still see one glitch:

![image](https://user-images.githubusercontent.com/8274816/89634178-3fcfae00-d8a5-11ea-8e3b-96e0d6f60da1.png)

If method name equals const name the extension still shows the value over the method.

**Comment by mrlacey** [comment]
> If method name equals const name the extension still shows the value over the method.

Definitely shouldn't be doing that! will investigate & fix

**Comment by MagicAndre1981** [comment]
ok, so we can close this and I should monitor #1 ?

**Comment by mrlacey** [comment]
> ok, so we can close this and I should monitor #1 ?

Yes please.
Feel free to raise issues for any other anomalies you find. I may be able to do workaround fixes. If not they'll be useful test cases for when #1 is implemented.

**Comment by MagicAndre1981** [comment]
Found a new case, with Xamarin.Forms, here I also see this value shown for Application which is wrong at this point:

![application_xamarin](https://user-images.githubusercontent.com/8274816/90600626-33c5e380-e1f7-11ea-818a-3675cb45a977.png)
