### ISSUE TITLE
Too much vertical displacement

### ISSUE THREAD

**Issue by LaraSQP** [mrlacey/ConstVisualizer#6]
The screenshot says it all.

![capture_001_04092021_074223](https://user-images.githubusercontent.com/12540983/132071841-3df9c179-14e2-441d-965e-b474634a774c.jpg)

Since I hopefully have your attention, btw, thank you very, very much for developing this and other extensions and making them and their source code available to all.

**Comment by mrlacey** [comment]
Thanks for flagging this.
Which version of Visual Studio are you seeing this on? and what font are you using?

**Comment by LaraSQP** [comment]
Visual Studio version: 16.11.1
ConstVisualizer version: 1.10
Font: DejaVu Sans Mono

I should have included the info in the original comment. Apologies.

**Comment by mrlacey** [comment]
Sorry for the delayed response. Recent illness has stopped me from working on anything but I hope to get to this eventually.

**Comment by mrlacey** [comment]
I've just added a new version (v1.14) that increases the space between the visualization and the line above.
I've tested with a number of different fonts and now don't see a version of the issue shown above but I don't have [the font mentioned](https://github.com/mrlacey/ConstVisualizer/issues/6#issuecomment-912930998) to be able to test with that.

---

[String Resource Visualizer](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer) has also been modified in an equivalent way too :)

**Comment by LaraSQP** [comment]
I have found the vs2020 update and it does increase the distance between the value and the line above.

However, what I meant is that there is too much vertical displacement between the value and the line **below** (and this still the case in the latest version).

In other words, my request was to put the value closer to the constant it decorates.

As it is, the values are always closer to the line above than to the line below and, to be honest, I fail to understand why.

You can see that easily in the image I provided in the first comment as well as in your own images in the main page.

![screenshot](https://user-images.githubusercontent.com/12540983/149261444-99934d56-1301-40cf-a542-385f38f7ce89.png)


![](https://user-images.githubusercontent.com/12540983/132071841-3df9c179-14e2-441d-965e-b474634a774c.jpg)

**Comment by mrlacey** [comment]
With the current spacing, I am relying on the information from the selected typeface to determine how much space to leave.
In your example, it looks like the typeface you're using leaves (or needs, or allows for) a lot of space between the baseline and the descender line. This looks like unnecessary padding based on the characters shown in the image.
With other fonts (like in the image below) even if there are parts of the glyph that use the full space of the Body height, they won't crash into each other. This was more of a concern in my original design than the inclusion of extra whitespace.

![image](https://user-images.githubusercontent.com/189547/149314990-825c70e0-9fb8-4198-9096-909e58098055.png)

What I don't want to have to try and do is determine how much white space there will be between the text of the file and what I'm adding above and so dynamically adjust the space accordingly. That feels like it would be a complex and time-consuming process that would impact development effort and, potentially, the responsiveness of the code.

Instead, how about I add manual configuration options to allow you to tweak the spacing?  
This will allow you to control the exact spacing to your requirements.

I'm thinking to add `Top Padding` and `Bottom Padding` options that take positive and negative integer values.
These would be zero by default but could be changed.
By making them positive integers you'd increase the spacing. 
By making them negative numbers you'd decrease the spacing.

Without implementing this and testing, I think setting `Bottom Padding` to "-2" or "-3" you'd get the behavior you desire.
Does this sound like a suitable solution?

**Comment by LaraSQP** [comment]
Those options would be the bee's knees. Thank you.

**Comment by mrlacey** [comment]
I've just published **v1.15** to the marketplace and it adds this functionality.



Default (current) behavior:
![image](https://user-images.githubusercontent.com/189547/149522577-b37d71f8-32a7-4c1d-b06c-8b961ab438d5.png)

And this is the new version, with bottom padding of "-4"
![image](https://user-images.githubusercontent.com/189547/149522788-6802d9bc-f193-4c95-a002-6d232ab1ab87.png)

Make the adjustments by going to Tools > Options > Const Visualizer
![image](https://user-images.githubusercontent.com/189547/149524375-2f7a28a0-41e9-468c-a8ab-b5c046736088.png)



Your mileage and experience will vary based on the fonts you use and if you have `const` values with descenders or other elements below the baseline.
This means that using a negative "Bottom padding" value could end up with something like this where you can't see all of the "g"
![image](https://user-images.githubusercontent.com/189547/149524192-b6eefffd-04c2-4b2a-9e07-ac3555e475a9.png)

---


If you have any problems, comments, or suggestions please raise another issue.
If you love it, please [leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ConstVisualizer&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey)  :smile:

**Comment by LaraSQP** [comment]
Great
