### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by xperiandri** [mrlacey/ConstVisualizer#7]

**Comment by mrlacey** [comment]
@xperiandri  This is on my list but is likely to take a few weeks before it gets done. (Hint: priority is partially determined by extensions that I know [my sponsors](https://github.com/sponsors/mrlacey) use 😉)

Also, I've never been particularly happy with the way this extension works and it has a lot of opportunities for improvement. I was considering a rewrite when porting to VS2022 but I assume you'd appreciate a port with current functionality and behavior before any such rewrite. Is this correct?

**Comment by xperiandri** [comment]
Actually it is not something urgent. I've just discovered that this extension exists. And I have VS 2022 only

**Comment by ktos** [comment]
I've just checked out of curiosity (discovered your extensions a few days ago, they are really great!) and it seems that simple retargeting to VS2022 is enough to make it work. I can prepare a PR if you would like.

**Comment by xperiandri** [comment]
@mrlacey. I guess the question is to you 🙂

**Comment by mrlacey** [comment]
There's a process and standardization I'm applying to all my VS extensions regarding adding VS2022 support while still maintaining a VS2019 version. 
There are also some other changes I'm making to all extensions too.
I hear the demand for this and will do it as quickly as I can.

**Comment by mrlacey** [comment]
version 1.11 has just been released to the marketplace and it adds support for Visual Studio 2022 as well as adding support for locally declared constants.

Any problems? - [raise a new issue](https://github.com/mrlacey/ConstVisualizer/issues/new).
Think **it's great**? - [Leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ConstVisualizer&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey) 😃
